import { PrismaClient } from '@prisma/client';

/**
 * Reuses the Prisma client generated by the core API (shared node_modules).
 * The realtime service only reads participants + writes tracking/chat rows.
 */
export const prisma = new PrismaClient({ log: ['error'] });
